{{- if and .Values.sessionSecret (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kcal.fullname" . }}
  labels:
    {{- include "kcal.labels" . | nindent 4 }}
type: Opaque
stringData:
  session-secret: {{ .Values.sessionSecret | quote }}
{{- end }}
